### ISSUE TITLE
Scrolling gives multiple hightlightes options in menu

### ISSUE THREAD

**Issue by Klaasvdb** [willemnelissen/willemnelissen.github.io#9]
![image](https://user-images.githubusercontent.com/6736069/135800520-960a2524-b0a1-4348-9f1f-3135774f5f52.png)

**Comment by twinters** [comment]
Fixed in https://github.com/willemnelissen/nsk-theatersport/commit/1d5e01985ff53a049160d7e24d1c029ee49b7f93
